config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :rooms
  resources :messages, only: [:create]
  
  get 'search', to: 'rooms#search', as: 'search_rooms'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room

  validates_presence_of :content
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
    
    before_create :set_opentok_id

    private

    def set_opentok_id
        opentok = OpenTok::OpenTok.new(ENV['VANAGE_API_KEY'], ENV['VANAGE_API_SECRET'])
        session = opentok.create_session
        self.vanage_session_id = session.session_id
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
        @message = Message.new(messages_params)

        if @message.save
            ActionCable.server.broadcast("chat_room_channel", @message)
        else
            redirect_to request.referrer, alert: 'Erro ao enviar mensagem! Tente novamente mais tarde.'
        end
    end

    private

    def messages_params
        params.require(:message).permit(:content, :room_id, :user)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :set_room, only: [:show]

    def create
        @room = Room.new
        
        if @room.save
            redirect_to "/rooms/#{@room.vanage_session_id}?user_name=#{params[:room][:user_name]}", notice: 'Sala criada com sucesso.'
        else
            redirect_to root_path, alert: 'Erro ao criar sala.'
        end
    end

    def show
        opentok = OpenTok::OpenTok.new(ENV['VANAGE_API_KEY'], ENV['VANAGE_API_SECRET'])
        @vanage_session_id = @room.vanage_session_id
        @token = opentok.generate_token(@vanage_session_id, {name: params[:user_name]})
    end

    def search
        room = Room.find_by(vanage_session_id: params[:room_url])
        
        if room.present?
            redirect_to "/rooms/#{room.vanage_session_id}?user_name=#{params[:user_name]}"
        else
            redirect_to root_path, alert: 'Nenhuma sala encontrada.'
        end
    end

    private 

    def set_room
        @room = Room.find_by(vanage_session_id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/_carousel.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="3" aria-label="Slide 4"></button>
    </div>

    <div class="carousel-inner">
        <div class="carousel-item active">
                <%= image_tag 'user_link', class: 'd-block w-100' %>

                <div class="text-center mt-2 mb-4 pb-2">
                    <h5>Criar um link para compartilhar</h5>
                    <p>
                        Clique em <strong>Nova reunião</strong> 
                        se quiser criar um link para enviar aos convidados.
                    </p>
                </div>
        </div>
            
        <div class="carousel-item">
            <%= image_tag 'meeting', class: 'd-block w-100' %>
            
            <div class="text-center mt-2 mb-4 pb-2">
                <h5>Ver todos juntos</h5>
                <p>
                    Para ver mais pessoas simultaneamente, selecione 
                    "Alterar layout" no menu "Mais opções".
                </p>
            </div>
        </div>
            
        <div class="carousel-item">
            <%= image_tag 'calendar', class: 'd-block w-100' %>
            
            <div class="text-center mt-2 mb-4 pb-2">
                <h5>Planejar com antecedência</h5>
                <p>
                    Clique em <strong>Nova reunião</strong> para 
                    programar reuniões no Google Agenda e enviar convites aos participantes.
                </p>
            </div>
        </div>

        <div class="carousel-item">
            <%= image_tag 'security', class: 'd-block w-100' %>
            
            <div class="text-center mt-2 mb-4 pb-2">
                <h5>Sua reunião está segura</h5>
                <p>
                    As pessoas só podem participar de uma reunião se o 
                    organizador convidar ou permitir.
                </p>
            </div>
        </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>

    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

app/views/home/_user_name_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="<%= action %>Modal" tabindex="-1" aria-labelledby="<%= action %>ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="<%= action %>ModalLabel">Como quer ser chamado na sala? :)</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <%= f.text_field :user_name, class: 'form-control', placeholder: 'Digite o Seu Nome', required: true %>
            </div>

            <div class="modal-footer">
                <%= button_tag nil, class: 'btn btn-primary p-2' do %>
                    Acessar
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="row home_content container">
    <div class="col-md mt-3">
        <h1>Videochamadas premium.</h1>
        <h1>Agora gratuitas para todos.</h1>

        <p>
            Reformulamos o Google Meet, 
            nosso serviço seguro para reuniões de negócios. 
            Agora ele é aberto e gratuito para todos.
        </p>

        <div class="mt-4 row">
            <div class="col-4">
                <%= form_with(model: Room.new) do |f| %>
                    <%= render "user_name_modal", f: f, action: "create" %>

                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">
                        <%= image_tag 'icons/video_call' %>
                        Nova reunião
                    </button>
                <% end %>
            </div>

            <div class="col-8">
                <%= form_with(url: search_rooms_path, method: :get) do |f| %>
                    <%= render "user_name_modal", f: f, action: "search" %>

                    <div class="input-group">
                        <%= image_tag 'icons/keyboard', class: 'me-2' %>
                        <%= f.text_field :room_url, class: 'form-control', placeholder: 'Digite um código ou link', required: true %>

                        <%= f.submit 'Acessar', class: 'submit_search', 'data-bs-toggle': "modal", 'data-bs-target': "#searchModal" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>

    <div class="col-md-4 offset-1 mt-3">
        <%= render 'carousel' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleMeet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>

    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= javascript_pack_tag 'alert' %>

    <%= render 'shared/navbar' %>
    
    <%= yield %>

    <%= render 'shared/footer' %>

    <!-- Alertas -->
    <% if alert %>
      <p class="alert alert-danger alert"><%= alert %></p>
    <% end %>

    <% if notice %>
      <p class="alert alert-success notice"><%= notice %></p>
    <% end %>
  </body>
</html>

app/views/rooms/_chat.html.erb
<%= javascript_pack_tag 'modal' %>
<%= javascript_pack_tag 'chat' %>

<!-- Modal -->
<div class="chat_modal">
    <h3>
        Mensagens na chamada
        <span class="float-end ms-4 close">X</span>
    </h3>

    <hr />

    <p>
        As mensagens só podem ser vistas pelas 
        pessoas na chamada e são excluídas quando ela termina.
    </p>

    <div id="messages">
        <% @room.messages.each do |message| %>
            <div class="mt-3">
                <small><%= message.user %> (<%= message.created_at.strftime("%d/%m/%Y %H:%M") %>)</small> <br />
                <%= message.content %>
            </div>
        <% end %>
    </div>

    <%= form_with(model: Message.new, remote: true) do |f| %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.hidden_field :user, value: params[:user_name] %>

        <div class="row">
            <div class="col-8">
                <%= f.text_field :content, class: 'form-control', placeholder: 'Digite algo para seus colegas :)' %>
            </div>

            <div class="col-4">
                <%= f.submit 'Enviar', class: 'btn btn-primary w-100', data: { disable_with: false } %>
            </div>
        </div>
    <% end %>
</div>

<!-- Button trigger modal -->
<button type="button" class="chat_btn m-2">
    <%= image_tag 'icons/message' %>
</button>

app/views/rooms/show.html.erb
<div class="container mt-4">
    <div class="mb-4">
        Código da sala: <b><%= params[:id] %></b>
    </div>

    <div class="row">
        <div id="videos"
            class="col"
            data-controller="vanage"
            data-vanage-token="<%= @token %>"
            data-vanage-api-key="<%= ENV['VANAGE_API_KEY'] %>"
            data-vanage-session-id="<%= @room.vanage_session_id %>"
            data-vanage-name="<%= params[:user_name] %>"></div>
    </div>
</div>

<%= render 'rooms/chat' %>

app/views/shared/_footer.html.erb
<footer class="text-center p-2 fixed-bottom">
    Made by <b>Lukita da Galera</b> S2
</footer>

app/views/shared/_navbar.html.erb
<nav class="text-center p-2 row">
    <div class="col">
        <%= link_to root_path do %>
            <%= image_tag 'logo', class: 'float-start' %>
        <% end %>
    </div>

    <div class="col text-center pt-1">
        <%= l(Time.now, format: "%H:%M • %a, %d de %B") %>
    </div>

    <div class="col">
        <%= image_tag 'perfil', class: 'float-end perfil_photo' %>
    </div>
</nav>